#!/bin/sh

docker_registry=$1

cat docker-images.list | grep -v "^#" | while read line
do
  echo "pulling $line"
  docker pull docker.io/vivalavida/${line//\//}
  docker tag docker.io/vivalavida/${line//\//} ${docker_registry}/${line}

  echo "pushing $line"
  docker push ${docker_registry}/${line}
  docker rmi docker.io/vivalavida/${line//\//}
  
  echo "pushed $line"
done
